name: 自动更新雾凇拼音词典到薄荷输入法

on:
  schedule:
    - cron: "0 15 5 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Mintimate'

    steps:
      - name: 检录本仓库
        uses: actions/checkout@v2

      - name: 设置环境变量
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装Python环境依赖
        run: |
          python -m pip install -r requirements.txt

      - name: 运行自动化脚本获取字典
        run: python main.py

      - name: 更新薄荷拼音目录
        run: |
          git clone https://github.com/Mintimate/oh-my-rime.git
          cp targetDict/* oh-my-rime/dicts/
          cd oh-my-rime
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          repository: Mintimate/oh-my-rime
          coauthor_name: gaboolic
          coauthor_email: 3831173+3831173@users.noreply.github.com
          directory: oh-my-rime/dicts
          message: "AutoUpdate Rime-frost Dicts"